### ISSUE TITLE
Artist details is not being rendered 

### ISSUE THREAD

**Issue by shivam-jha2712** [adrianhajdin/project_music_player#22]
![Screenshot (151)](https://user-images.githubusercontent.com/71783722/207404480-0617f101-9d54-422b-b753-76d1984f1e8d.png)
![Screenshot (152)](https://user-images.githubusercontent.com/71783722/207404722-0f7a3755-1535-4e6c-8d81-14963c1e910c.png)
![Screenshot (153)](https://user-images.githubusercontent.com/71783722/207404750-48429002-e5a9-43d5-a95c-fb5d3d353baa.png)

Have done everything as the video suggested also some people are suggesting going for v2 in builder #20  but even that is not working. So what should I do as

**Comment by kadircanyzc** [comment]
How did you do?
