### ISSUE TITLE
Top Play component is unable to fetch artist details in line no 112

### ISSUE THREAD

**Issue by shivam-jha2712** [adrianhajdin/project_music_player#24]
Please help us with that as the error is coming in line number 112 (in your code) In my code it is 117. 
![Screenshot (166)](https://user-images.githubusercontent.com/71783722/208420410-8f17e69f-b437-4d23-a336-6a99e8666cd5.png)

**Comment by weichi2002** [comment]
I figured it out. It's not because there are any issues with the code, but rather the API is prolly up to its limit. Only 500 songs per month hard limits. Also nice github portfolio.

**Comment by stevensps** [comment]
> I figured it out. It's not because there are any issues with the code, but rather the API is prolly up to its limit. Only 500 songs per month hard limits. Also nice github portfolio.

I don't believe this is the issue. I am experiencing the same issue as in the screenshot above and just checked my RapidAPI analytics dashboard. I have only made 101 API calls in the last 30 days. Still looking for a solution.

![image](https://user-images.githubusercontent.com/121136356/208779762-c78c0bc9-629a-4289-bb06-53bf97992bfb.png)
![image](https://user-images.githubusercontent.com/121136356/208779815-6de724c8-ebef-4831-9c6c-dab49615f8ca.png)

**Comment by stevensps** [comment]
I figured it out. By console logging the topPlays array, I was able to see that ShazamAPI modified their structure. So, to fix the topPlays error you need to do the following steps. I really hope this helps! I'm still testing but am at least able to get my page back to play songs.

1) Update base URL and sub endpoint queries in ShazamCoreAPI
![image](https://user-images.githubusercontent.com/121136356/209004611-fd48d681-d805-4f0d-aec0-3fc503f421a9.png)

2) Navigate to topPlays and console log the topPlays array. If you notice in the screenshot below, another "0" is now added to the array structure.
![image](https://user-images.githubusercontent.com/121136356/209004771-ab964266-a21c-47b4-85d5-c52955413033.png)

3) This causes the need to update the code in the screenshot below, and anywhere else with this code structure in TopPlays. Keep refreshing the page and the console log will tell you the lines that you need to update.
![image](https://user-images.githubusercontent.com/121136356/209005410-a5ea80bd-d4fd-4686-821f-ef1782cc4afc.png)

**Comment by weichi2002** [comment]
@TallestStatue23 Thank you. I tried your method and it worked for a little while. But now I am getting  this

<img width="491" alt="image" src="https://user-images.githubusercontent.com/92957081/209050703-4fb8c97e-6dae-4f80-aef7-1b40d5107a85.png">

Do you know what this might be. Thank you very much.

**Comment by shivam-jha2712** [comment]
> I figured it out. It's not because there are any issues with the code, but rather the API is prolly up to its limit. Only 500 songs per month hard limits. Also nice github portfolio.

Thanks for the Appreciation 😁. And yes the solution proposed by @TallestStatue23  does work.

**Comment by shivam-jha2712** [comment]
> I figured it out. By console logging the topPlays array, I was able to see that ShazamAPI modified their structure. So, to fix the topPlays error you need to do the following steps. I really hope this helps! I'm still testing but am at least able to get my page back to play songs.
> 
> 1. Update base URL and sub endpoint queries in ShazamCoreAPI
>    ![image](https://user-images.githubusercontent.com/121136356/209004611-fd48d681-d805-4f0d-aec0-3fc503f421a9.png)
> 2. Navigate to topPlays and console log the topPlays array. If you notice in the screenshot below, another "0" is now added to the array structure.
>    ![image](https://user-images.githubusercontent.com/121136356/209004771-ab964266-a21c-47b4-85d5-c52955413033.png)
> 3. This causes the need to update the code in the screenshot below, and anywhere else with this code structure in TopPlays. Keep refreshing the page and the console log will tell you the lines that you need to update.
>    ![image](https://user-images.githubusercontent.com/121136356/209005410-a5ea80bd-d4fd-4686-821f-ef1782cc4afc.png)

Thanks this helps to save the trouble and thanks for the solution
