### ISSUE TITLE
The API has shifted to the paid version use only. 

### ISSUE THREAD

**Issue by shivam-jha2712** [adrianhajdin/project_music_player#27]
@adrianhajdin  Could you please make updates as per the Spotify API to make it working.

**Comment by sdo-piyush** [comment]
did anyone complete it ? with any other api?????

**Comment by Hoanguyen-2002** [comment]
can u complete it with free API ?

**Comment by shivam-jha2712** [comment]
There exists no free API anymore !! @Hoanguyen-2002

**Comment by MeggaBug** [comment]
@shivam-jha2712 There is a free API now. Another Shazam Core it seems different, there's a few other options as well. Would any work and if not what need is it missing?
