### ISSUE TITLE
The Source is not being fetched 

### ISSUE THREAD

**Issue by shivam-jha2712** [adrianhajdin/project_music_player#30]
Can you help me the source is not being fetched 
![Screenshot (229)](https://user-images.githubusercontent.com/71783722/213903322-f8e626d1-d8fa-4a03-ba52-15434df3782a.png)

**Comment by shivam-jha2712** [comment]
can you help me with this error

**Comment by humza-dev** [comment]
Did you completed the project?

**Comment by shivam-jha2712** [comment]
Yes, the project is completed but the problem is that they have switched the API version from free to paid and thus, you cannot run it without paying the subscription fee. If in your case you have solved this issue then please do let me know about it. It will help me tons.

**Comment by humza-dev** [comment]
I have but can you suggest me some project vedios with no paid apis,need it for resume

**Comment by shivam-jha2712** [comment]
Ya you can build that https://www.youtube.com/watch?v=EyIvuigqDoA - Image Generation
