### ISSUE TITLE
Mobile issue

### ISSUE THREAD

**Issue by aniket-kes** [adrianhajdin/project_music_player#37]
Everything is working good but after deploying the app on netlify, i opened the link using my mobile handset, i noticed there is no search bar and hamburger menu.  Also when i am clicking to see more in top charts app gets crashed in mobile device but the irony is when i inspecting through my laptop using responsiveness everything is good but in mobile device i don't understand what the problem is.

**Comment by Hoanguyen-2002** [comment]
can u run the shazam core api, i cant pay for the basic plan , or are you suggest any alternative api ?

**Comment by aniket-kes** [comment]
> can u run the shazam core api, i cant pay for the basic plan , or are you suggest any alternative api ?

No i haven't bought shazam core API, I've used shazam API as alternative because it is free and most of the functionality are same just need to see json tree and you will get your data, you can refer my repo called music player. 

Also the issue has been partially resolved i am getting search bar and hamburger menu in mobile device but the problem is when i am clicking on the song to get song details or artist detail app gets crashed after deployment on netlify but working good in localhost.

**Comment by Hoanguyen-2002** [comment]
oh tks for your recommendation, it works well, but do you know how to expand the song duration ? every song cant play full and it just play 1:29

**Comment by Hoanguyen-2002** [comment]
oh if you want to run with netlify you can add --host after npm run dev like : npm run dev --host

**Comment by aniket-kes** [comment]
> oh tks for your recommendation, it works well, but do you know how to expand the song duration ? every song cant play full and it just play 1:29

ig we cannot play full song using shazam api

**Comment by Hoanguyen-2002** [comment]
i can't filter song by genre with shazam api, can u help me ?

**Comment by aniket-kes** [comment]
> i can't filter song by genre with shazam api, can u help me ?

Same here because we don't have songs based on genre as an endpoint, this feature is on shazam core. Hence we cannot use this functionality also the around you page is of no use for shazam api users as it doesn't have an endpoint to play track based on the country. 

But you can try one thing, see we have genre in our song details right so what we can to is when we click on any genre let's say pop so we can match all the songs which have pop as a genre and display it on our discover page but this logic is worthless in case of shazam core because they have this endpoint.

**Comment by aniket-kes** [comment]
> oh if you want to run with netlify you can add --host after npm run dev like : npm run dev --host

Thanks for your advice i did but certainly it didn't worked hence what i did is created one __redirect file in my main folder and added this line inside it  
```
/*    /index.html   200 
``` 
![image](https://github.com/adrianhajdin/project_music_player/assets/99314074/d8f365b9-80f5-4dc7-9284-6d50da353d7c)

And that's it my problem got solved. 

But in mobile devices the page starts from bottom, i want it to start from top if you guys have any idea about this please let me know.

**Comment by Hoanguyen-2002** [comment]
when i use shazam api i cant get artist detail, can you explain why

**Comment by aniket-kes** [comment]
> when i use shazam api i cant get artist detail, can you explain why

change the endpoint to artists/get-details?id=${artistId} when you create a query it will look something like this 
```javascript
getArtistDetails: builder.query({query:(artistId)=>`/artists/get-details?id=${artistId}`}),
```

**Comment by Fakokunde** [comment]
when i tried the shazam api, i couldn't get the song images as it wasnt in the data array. had to settle for another api. The problem now is when i click on a song, every other song play at the same time and when i pause all the other songs pause too. and the musicplayer components are not displaying

**Comment by aniket-kes** [comment]
> 

You can refer my github repo for shazam API but the other problem which you have stated every other song is also playing this happened to me when i searched some song and in search i got 2-3 same song title when i clicked on any one othe which have same name is also started playing because we are taking consideration of song title in play pause component if we do it using song id then the issue can be resolve. Without code i can conclude this much only

**Comment by aniket-kes** [comment]
Which api are you using instead of shazam now?

**Comment by Fakokunde** [comment]
I'm using Genius - song lyrics. 
 
This is my songcard component
<img width="672" alt="image" src="https://github.com/adrianhajdin/project_music_player/assets/125125735/80af4cc7-6db9-4822-9bb8-15980aa928f6">
<img width="430" alt="image" src="https://github.com/adrianhajdin/project_music_player/assets/125125735/3aee6d0f-f122-46f3-a263-f054d9cb7376">

This is my discover component
<img width="656" alt="image" src="https://github.com/adrianhajdin/project_music_player/assets/125125735/a4903614-cb0c-4de1-9e08-14131f91b278">
<img width="641" alt="image" src="https://github.com/adrianhajdin/project_music_player/assets/125125735/0aa010ad-7a40-4da4-a447-7798ce665f31">
